version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: nestdb
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: